spring.application.name=eventportal

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/eventportal
spring.datasource.username=postgres
spring.datasource.password=student
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kolhapuruniversityevents@gmail.com
spring.mail.password=tvwhysykhyxjjwvf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

# Multipart Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Stripe Configuration (Test Mode)
stripe.secret.key=sk_test_51T8ltFDEFKUpmmXqYdVsV949seEd1wMl47SN2qbxPc55J7eh9CVcMDsjl2bPHBpqyEJ1PYuagphIydb4eamq91Ud00iiISy1eQ
stripe.publishable.key=pk_test_51T8ltFDEFKUpmmXqcvs0oLRPCjpmhyZcQsaja2aMcERhpaAqqVXC7Zp2EGrsdIG2rfBQ2RuR4tQdhxGYVxsOQS2q00Ol216AsQ
